=== jthy/Projekt/WBA_OrderHero/src/BoersenEintrag.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="BoersenEintrag">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="BoerseneintragsID" type="xs:integer" maxOccurs="1" minOccurs="1"/>		
						<xs:element ref="Person"/>
					 	<xs:element name="Erstellungsdatum" type="xs:dateTime" />
						<xs:element name="Titel" type="xs:string" />
						<xs:element name="Informationstext" type="xs:string" />
						<xs:element name="Startdatum" type="xs:dateTime" />
						<xs:element name="Ablaufdatum" type="xs:dateTime" />
						<xs:element name="Kommentare">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="Person"/>
								<xs:element name="Datum" type="xs:dateTime" />
								<xs:element name="Informationstext" type="xs:string" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Typ">
					 	<xs:simpleType>
					    	<xs:restriction base="xs:string">
					      		<xs:enumeration value="Angebot" />
					      		<xs:enumeration value="Gesuch" />
					   		</xs:restriction>
					  	</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	<!-- Definitionen -->			
	<xs:element name="Person">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Typ">
	 			<xs:simpleType>
			    	<xs:restriction base="xs:string">
			      		<xs:enumeration value="Gastronom" />
			      		<xs:enumeration value="Lieferant" />
			   		</xs:restriction>
	  			</xs:simpleType>
	  		</xs:element>
			<xs:element name="Vorname" type="xs:string" />
			<xs:element name="Nachname" type="xs:string"/>
			<!-- Gastronom muss über 18 sein um Käufe abzuwickeln -->
			<xs:element name="Alter">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="18" />
						<xs:maxInclusive value="100" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element ref="Betrieb"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
			
<xs:element name="Betrieb">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Betriebs_ID" type="xs:integer" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Betriebname" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Adresse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="strasse" type="xs:string"/>
						<xs:element name="Hausnummer" type="xs:integer"/>
						<xs:element name="PLZ">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:pattern value="(D )?[0-9]{5}" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Art_des_Betriebes" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== jthy/Projekt/WBA_OrderHero/src/BoersenEintrag.xml
<?xml version="1.0" encoding="UTF-8"?>
<BoersenEintrag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../BoersenEintrag.xsd">
  <BoerseneintragsID>0</BoerseneintragsID>
  <Person>
    <Typ>Gastronom</Typ>
    <Vorname>Alex</Vorname>
    <Nachname>Nachname</Nachname>
    <Alter>32</Alter>
    <Betrieb>
      <Betriebs_ID>0</Betriebs_ID>
      <Betriebname>Betriebname</Betriebname>
      <Adresse>
        <Straße>Straße</Straße>
        <Hausnummer>0</Hausnummer>
        <PLZ>32312</PLZ>
      </Adresse>
      <Art_des_Betriebes>Art_des_Betriebes</Art_des_Betriebes>
    </Betrieb>
  </Person>
  <Erstellungsdatum>2001-12-31T12:00:00</Erstellungsdatum>
  <Titel>Titel</Titel>
  <Informationstext>Informationstext</Informationstext>
  <Startdatum>2001-12-31T12:00:00</Startdatum>
  <Ablaufdatum>2001-12-31T12:00:00</Ablaufdatum>
  <Kommentare>
    <Person>
      <Typ>Gastronom</Typ>
      <Vorname>Vorname</Vorname>
      <Nachname>Nachname</Nachname>
      <Alter>90</Alter>
      <Betrieb>
        <Betriebs_ID>0</Betriebs_ID>
        <Betriebname>Betriebname</Betriebname>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>12345</PLZ>
        </Adresse>
        <Art_des_Betriebes>Art_des_Betriebes</Art_des_Betriebes>
      </Betrieb>
    </Person>
    <Datum>2001-12-31T12:00:00</Datum>
    <Informationstext>Informationstext</Informationstext>
  </Kommentare>
  <Typ>Angebot</Typ>
</BoersenEintrag>
