=== jthy/Projekt/WBA_OrderHero/bin/XSD/Betriebliste.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Betriebliste">
<xs:complexType>
<xs:sequence>
<xs:element name="Betrieb" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Betriebs_ID" type="xs:int" minOccurs="1" maxOccurs="1"/>
						<xs:element name="Betriebname" minOccurs="1" maxOccurs="1" type="xs:string"/>
						<xs:element name="Adresse">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="strasse" type="xs:string"/>
									<xs:element name="Hausnummer" type="xs:int"/>
									<xs:element name="PLZ">
										<xs:simpleType>
											<xs:restriction base="xs:int">
											<xs:pattern value="(D )?[0-9]{5}" />
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== jthy/Projekt/WBA_OrderHero/bin/XML/Betriebliste.xml
<?xml version="1.0" encoding="UTF-8"?>
<Betriebliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/Betriebliste.xsd">
  <Betrieb>
    <Betriebs_ID>1</Betriebs_ID>
    <Betriebname>Beuek</Betriebname>
    <Adresse>
      <strasse>Neutor</strasse>
      <Hausnummer>2</Hausnummer>
      <PLZ>12345</PLZ>
    </Adresse>
    <Art_des_Betriebes>Restaurant</Art_des_Betriebes>
  </Betrieb>
   <Betrieb>
    <Betriebs_ID>2</Betriebs_ID>
    <Betriebname>Knaller</Betriebname>
    <Adresse>
      <strasse>Lilysallee</strasse>
      <Hausnummer>933</Hausnummer>
      <PLZ>12345</PLZ>
    </Adresse>
    <Art_des_Betriebes>Grosshandel</Art_des_Betriebes>
  </Betrieb>
</Betriebliste>
