=== jthy/Projekt/WBA_OrderHero/bin/XSD/KundenLieferantenListe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

<xs:element name="KundenLieferantenListe">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Person"/>
			<xs:element ref="Bestellung" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>	

<!-- Definitionen -->
<xs:element name="Bestellung">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Bestellungs_ID" type ="xs:integer"/>
			<xs:element name="Lieferdatum" type="xs:date"/>
			<xs:element ref="Person"/>
			<xs:element ref="Betrieb"/>
			<xs:element ref="Person"/>
			<xs:element ref="Betrieb"/>
			<xs:element name="Anzahl" type="xs:integer"/>
			<xs:element ref="Produkt"/>
			<xs:element name="Bestellungsart">
				<xs:simpleType>
    				<xs:restriction base="xs:string">
        				<xs:enumeration value="Dauerauftrag"/>
						<xs:enumeration value="Einmalige_Bestellung"/>
					</xs:restriction>
				</xs:simpleType>                         
			</xs:element>
			<xs:element name="Zahlungsart">
  				<xs:simpleType>
    				<xs:restriction base="xs:string">
      					<xs:enumeration value="Rechnung" />
      					<xs:enumeration value="Lastschrift" />
      					<xs:enumeration value="Vorkasse" />
      					<xs:enumeration value="PayPal" />
      					<xs:enumeration value="Kreditkarte" />
   				 	</xs:restriction>
  				</xs:simpleType>
			</xs:element>			
			<xs:element name="Gesamtbetrag_Bestellung" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="Person">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Typ">
	 			<xs:simpleType>
			    	<xs:restriction base="xs:string">
			      		<xs:enumeration value="Gastronom" />
			      		<xs:enumeration value="Lieferant" />
			   		</xs:restriction>
	  			</xs:simpleType>
	  		</xs:element>
			<xs:element name="Vorname" type="xs:string" />
			<xs:element name="Nachname" type="xs:string"/>
			<!-- Gastronom muss über 18 sein um Käufe abzuwickeln -->
			<xs:element name="Alter">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="18" />
						<xs:maxInclusive value="100" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element ref="Betrieb"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
			
<xs:element name="Betrieb">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Betriebs_ID" type="xs:integer" minOccurs="1" maxOccurs="1"/>
						<xs:element name="Betriebname" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="Adresse">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Straße" type="xs:string"/>
									<xs:element name="Hausnummer" type="xs:integer"/>
									<xs:element name="PLZ">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
											<xs:pattern value="(D )?[0-9]{5}" />
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
</xs:element>	

<xs:element name="Produkt">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Produkt_ID" type="xs:integer" />
			<xs:element name="Produktname" type="xs:string" />
			<xs:element name="Preis_in_Euro" type="xs:float" />
			<xs:element name="Beschreibung" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:element>


</xs:schema>

=== jthy/Projekt/WBA_OrderHero/src/XML/KundenLieferantenListe.xml
<?xml version="1.0" encoding="UTF-8"?>
<KundenLieferantenListe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/KundenLieferantenListe.xsd">
  <Person>
    <Typ>Gastronom</Typ>
    <Vorname>Vorname</Vorname>
    <Nachname>Nachname</Nachname>
    <Alter>0</Alter>
    <Betrieb>
      <Betriebs_ID>0</Betriebs_ID>
      <Betriebname>Betriebname</Betriebname>
      <Adresse>
        <Straße>Straße</Straße>
        <Hausnummer>0</Hausnummer>
        <PLZ>0</PLZ>
      </Adresse>
    </Betrieb>
  </Person>
  <Bestellung>
    <Bestellungs_ID>0</Bestellungs_ID>
    <Lieferdatum>2001-01-01</Lieferdatum>
    <Person>
      <Typ>Gastronom</Typ>
      <Vorname>Vorname</Vorname>
      <Nachname>Nachname</Nachname>
      <Alter>0</Alter>
      <Betrieb>
        <Betriebs_ID>0</Betriebs_ID>
        <Betriebname>Betriebname</Betriebname>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
    </Person>
    <Betrieb>
      <Betriebs_ID>0</Betriebs_ID>
      <Betriebname>Betriebname</Betriebname>
      <Adresse>
        <Straße>Straße</Straße>
        <Hausnummer>0</Hausnummer>
        <PLZ>0</PLZ>
      </Adresse>
    </Betrieb>
    <Person>
      <Typ>Gastronom</Typ>
      <Vorname>Vorname</Vorname>
      <Nachname>Nachname</Nachname>
      <Alter>0</Alter>
      <Betrieb>
        <Betriebs_ID>0</Betriebs_ID>
        <Betriebname>Betriebname</Betriebname>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
    </Person>
    <Betrieb>
      <Betriebs_ID>0</Betriebs_ID>
      <Betriebname>Betriebname</Betriebname>
      <Adresse>
        <Straße>Straße</Straße>
        <Hausnummer>0</Hausnummer>
        <PLZ>0</PLZ>
      </Adresse>
    </Betrieb>
    <Anzahl>0</Anzahl>
    <Produkt>
      <Produkt_ID>0</Produkt_ID>
      <Produktname>Produktname</Produktname>
      <Preis_in_Euro>0.0</Preis_in_Euro>
      <Beschreibung>Beschreibung</Beschreibung>
    </Produkt>
    <Bestellungsart>Dauerauftrag</Bestellungsart>
    <Zahlungsart>Rechnung</Zahlungsart>
    <Gesamtbetrag_Bestellung>0</Gesamtbetrag_Bestellung>
  </Bestellung>
</KundenLieferantenListe>
