=== jthy/Projekt/WBA_OrderHero/bin/XSD/OrderHero.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="OrderHero">
<xs:complexType>
<xs:sequence>

<xs:element name="Bestand">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Produkt"/>
			<xs:element name="Anzahl" type="xs:integer"/>
			<xs:element name="Verfuegbarkeit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="verfuegbar"/>
						<xs:enumeration value="momentan_nicht_verfuegbar"/>
					</xs:restriction>
				</xs:simpleType>                         
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element> 

<xs:element name="Bestellungsliste">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Bestellung"/>
		</xs:sequence>	
	</xs:complexType>
</xs:element>


<xs:element name="Boerse">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Eintrag">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="BoerseneintragsID" type="xs:integer" maxOccurs="1" minOccurs="1"/>	
						<xs:element ref="Person"/>
					 	<xs:element name="Erstellungsdatum" type="xs:dateTime" />
						<xs:element name="Titel" type="xs:string" />
						<xs:element name="Informationstext" type="xs:string" />
						<xs:element name="Startdatum" type="xs:dateTime" />
						<xs:element name="Ablaufdatum" type="xs:dateTime" />
						<xs:element name="Kommentare">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="Person"/>
								<xs:element name="Datum" type="xs:dateTime" />
								<xs:element name="Informationstext" type="xs:string" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Typ">
					 	<xs:simpleType>
					    	<xs:restriction base="xs:string">
					      		<xs:enumeration value="Angebot" />
					      		<xs:enumeration value="Gesuch" />
					   		</xs:restriction>
					  	</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	  </xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="KundenLieferantenListe">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Person"/>
			<xs:element ref="Bestellung" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="Produkte">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Produkt"/>
			<xs:element name="Verfuegbarkeit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="verfuegbar"/>
						<xs:enumeration value="momentan_nicht_verfuegbar"/>
					</xs:restriction>
				</xs:simpleType>                         
			</xs:element>
			<xs:element ref="Person"/>
		</xs:sequence>
	</xs:complexType>
</xs:element> 

</xs:sequence>
</xs:complexType>
</xs:element>


<xs:element name="Bestellung">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Bestellungs_ID" type ="xs:integer"/>
			<xs:element name="Lieferdatum" type="xs:date"/>
			<xs:element ref="Person"/>
			<xs:element ref="Betrieb"/>
			<xs:element ref="Person"/>
			<xs:element ref="Betrieb"/>
			<xs:element name="Anzahl" type="xs:integer"/>
			<xs:element ref="Produkt"/>
			<xs:element name="Bestellungsart">
				<xs:simpleType>
    				<xs:restriction base="xs:string">
        				<xs:enumeration value="Dauerauftrag"/>
						<xs:enumeration value="Einmalige_Bestellung"/>
					</xs:restriction>
				</xs:simpleType>                         
			</xs:element>
			<xs:element name="Zahlungsart">
  				<xs:simpleType>
    				<xs:restriction base="xs:string">
      					<xs:enumeration value="Rechnung" />
      					<xs:enumeration value="Lastschrift" />
      					<xs:enumeration value="Vorkasse" />
      					<xs:enumeration value="PayPal" />
      					<xs:enumeration value="Kreditkarte" />
   				 	</xs:restriction>
  				</xs:simpleType>
			</xs:element>			
			<xs:element name="Gesamtbetrag_Bestellung" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>


<xs:element name="Person">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Typ">
	 			<xs:simpleType>
			    	<xs:restriction base="xs:string">
			      		<xs:enumeration value="Gastronom" />
			      		<xs:enumeration value="Lieferant" />
			   		</xs:restriction>
	  			</xs:simpleType>
	  		</xs:element>
			<xs:element name="Vorname" type="xs:string"/>
			<xs:element name="Nachname" type="xs:string"/>
			<!-- Gastronom muss über 18 sein um Käufe abzuwickeln -->
			<xs:element name="Alter">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="18" />
						<xs:maxInclusive value="100" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element ref="Betrieb"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
			
<xs:element name="Betrieb">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Betriebs_ID" type="xs:integer" minOccurs="1" maxOccurs="1"/>
						<xs:element name="Betriebname" minOccurs="1" maxOccurs="1" />
						<xs:element name="Adresse">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Straße" type="xs:string"/>
									<xs:element name="Hausnummer" type="xs:integer"/>
									<xs:element name="PLZ">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
											<xs:pattern value="(D )?[0-9]{5}" />
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
</xs:element>

<xs:element name="Produkt">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Produkt_ID" type="xs:integer"/>
						<xs:element name="Produktangaben">	
							<xs:complexType>
								<xs:sequence> 
									<xs:element name="Produktname" type="xs:string" />
									<xs:element name="Preis_in_Euro" type="xs:float" />
									<xs:element name="Beschreibung" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
</xs:element>

</xs:schema>

=== jthy/Projekt/WBA_OrderHero/src/OrderHero.xml
<?xml version="1.0" encoding="UTF-8"?>
<OrderHero xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OrderHero.xsd">
  <Bestand>
    <Produkt>
      <Produkt_ID>0</Produkt_ID>
      <Produktangaben>
        <Produktname>Produktname</Produktname>
        <Preis_in_Euro>0.0</Preis_in_Euro>
        <Beschreibung>Beschreibung</Beschreibung>
      </Produktangaben>
    </Produkt>
    <Anzahl>0</Anzahl>
    <Verfuegbarkeit>verfuegbar</Verfuegbarkeit>
  </Bestand>
  <Bestellungsliste>
    <Bestellung>
      <Bestellungs_ID>0</Bestellungs_ID>
      <Lieferdatum>2001-01-01</Lieferdatum>
      <Person>
        <Typ>Gastronom</Typ>
        <Vorname>Vorname</Vorname>
        <Nachname>Nachname</Nachname>
        <Alter>0</Alter>
        <Betrieb>
          <Betriebname/>
          <Adresse>
            <Straße>Straße</Straße>
            <Hausnummer>0</Hausnummer>
            <PLZ>0</PLZ>
          </Adresse>
        </Betrieb>
      </Person>
      <Betrieb>
        <Betriebname/>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
      <Person>
        <Typ>Gastronom</Typ>
        <Vorname>Vorname</Vorname>
        <Nachname>Nachname</Nachname>
        <Alter>0</Alter>
        <Betrieb>
          <Betriebname/>
          <Adresse>
            <Straße>Straße</Straße>
            <Hausnummer>0</Hausnummer>
            <PLZ>0</PLZ>
          </Adresse>
        </Betrieb>
      </Person>
      <Betrieb>
        <Betriebname/>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
      <Anzahl>0</Anzahl>
      <Produkt>
        <Produkt_ID>0</Produkt_ID>
        <Produktangaben>
          <Produktname>Produktname</Produktname>
          <Preis_in_Euro>0.0</Preis_in_Euro>
          <Beschreibung>Beschreibung</Beschreibung>
        </Produktangaben>
      </Produkt>
      <Bestellungsart>Dauerauftrag</Bestellungsart>
      <Zahlungsart>Rechnung</Zahlungsart>
      <Gesamtbetrag_Bestellung>0</Gesamtbetrag_Bestellung>
    </Bestellung>
  </Bestellungsliste>
  <Boerse>
    <Eintrag>
      <Person>
        <Typ>Gastronom</Typ>
        <Vorname>Vorname</Vorname>
        <Nachname>Nachname</Nachname>
        <Alter>0</Alter>
        <Betrieb>
          <Betriebname/>
          <Adresse>
            <Straße>Straße</Straße>
            <Hausnummer>0</Hausnummer>
            <PLZ>0</PLZ>
          </Adresse>
        </Betrieb>
      </Person>
      <Erstellungsdatum>2001-12-31T12:00:00</Erstellungsdatum>
      <Titel>Titel</Titel>
      <Informationstext>Informationstext</Informationstext>
      <Startdatum>2001-12-31T12:00:00</Startdatum>
      <Ablaufdatum>2001-12-31T12:00:00</Ablaufdatum>
      <Kommentare>
        <Person>
          <Typ>Gastronom</Typ>
          <Vorname>Vorname</Vorname>
          <Nachname>Nachname</Nachname>
          <Alter>0</Alter>
          <Betrieb>
            <Betriebname/>
            <Adresse>
              <Straße>Straße</Straße>
              <Hausnummer>0</Hausnummer>
              <PLZ>0</PLZ>
            </Adresse>
          </Betrieb>
        </Person>
        <Datum>2001-12-31T12:00:00</Datum>
        <Informationstext>Informationstext</Informationstext>
      </Kommentare>
      <Typ>Angebot</Typ>
    </Eintrag>
  </Boerse>
  <Geschaeftspartnerliste>
    <Listentyp>Kundenliste</Listentyp>
    <Person>
      <Typ>Gastronom</Typ>
      <Vorname>Vorname</Vorname>
      <Nachname>Nachname</Nachname>
      <Alter>0</Alter>
      <Betrieb>
        <Betriebname/>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
    </Person>
    <Bestellung>
      <Bestellungs_ID>0</Bestellungs_ID>
      <Lieferdatum>2001-01-01</Lieferdatum>
      <Person>
        <Typ>Gastronom</Typ>
        <Vorname>Vorname</Vorname>
        <Nachname>Nachname</Nachname>
        <Alter>0</Alter>
        <Betrieb>
          <Betriebname/>
          <Adresse>
            <Straße>Straße</Straße>
            <Hausnummer>0</Hausnummer>
            <PLZ>0</PLZ>
          </Adresse>
        </Betrieb>
      </Person>
      <Betrieb>
        <Betriebname/>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
      <Person>
        <Typ>Gastronom</Typ>
        <Vorname>Vorname</Vorname>
        <Nachname>Nachname</Nachname>
        <Alter>0</Alter>
        <Betrieb>
          <Betriebname/>
          <Adresse>
            <Straße>Straße</Straße>
            <Hausnummer>0</Hausnummer>
            <PLZ>0</PLZ>
          </Adresse>
        </Betrieb>
      </Person>
      <Betrieb>
        <Betriebname/>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
      <Anzahl>0</Anzahl>
      <Produkt>
        <Produkt_ID>0</Produkt_ID>
        <Produktangaben>
          <Produktname>Produktname</Produktname>
          <Preis_in_Euro>0.0</Preis_in_Euro>
          <Beschreibung>Beschreibung</Beschreibung>
        </Produktangaben>
      </Produkt>
      <Bestellungsart>Dauerauftrag</Bestellungsart>
      <Zahlungsart>Rechnung</Zahlungsart>
      <Gesamtbetrag_Bestellung>0</Gesamtbetrag_Bestellung>
    </Bestellung>
  </Geschaeftspartnerliste>
  <Produkte>
    <Produkt>
      <Produkt_ID>0</Produkt_ID>
      <Produktangaben>
        <Produktname>Produktname</Produktname>
        <Preis_in_Euro>0.0</Preis_in_Euro>
        <Beschreibung>Beschreibung</Beschreibung>
      </Produktangaben>
    </Produkt>
    <Verfuegbarkeit>verfuegbar</Verfuegbarkeit>
    <Person>
      <Typ>Gastronom</Typ>
      <Vorname>Vorname</Vorname>
      <Nachname>Nachname</Nachname>
      <Alter>0</Alter>
      <Betrieb>
        <Betriebname/>
        <Adresse>
          <Straße>Straße</Straße>
          <Hausnummer>0</Hausnummer>
          <PLZ>0</PLZ>
        </Adresse>
      </Betrieb>
    </Person>
  </Produkte>
</OrderHero>
