=== jthy/Projekt/WBA_OrderHero/bin/Bestandsliste.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Bestand">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Produkt"/>
			<xs:element name="Anzahl" type="xs:integer"/>
			<xs:element name="Verfuegbarkeit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="verfuegbar"/>
						<xs:enumeration value="momentan_nicht_verfuegbar"/>
					</xs:restriction>
				</xs:simpleType>                         
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element> 

<!-- Definitionen -->			
<xs:element name="Produkt">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Produkt_ID" type="xs:integer"/>
			<xs:element name="Produktangaben">	
				<xs:complexType>
					<xs:sequence> 
						<xs:element name="Produktname" type="xs:string" />
						<xs:element name="Preis_in_Euro" type="xs:float" />
						<xs:element name="Beschreibung" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
						
</xs:schema>

=== jthy/Projekt/WBA_OrderHero/bin/Bestandsliste.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bestand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Bestandsliste.xsd">
  <Produkt>
    <Produkt_ID>0</Produkt_ID>
    <Produktangaben>
      <Produktname>Produktname</Produktname>
      <Preis_in_Euro>0.0</Preis_in_Euro>
      <Beschreibung>Beschreibung</Beschreibung>
    </Produktangaben>
  </Produkt>
  <Anzahl>0</Anzahl>
  <Verfuegbarkeit>verfuegbar</Verfuegbarkeit>
</Bestand>
