=== jthy/Projekt/WBA_OrderHero/bin/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Rezepte">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Rezept" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Rezept">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Titel" type="xs:string"/>
				<xs:element name="Untertitel" type="xs:string" minOccurs="0"/>
				<xs:element ref="Kategorie"/>
				<xs:element ref="Bilder" minOccurs="0"/>
				<xs:element ref="Zutaten"/>
				<xs:element ref="Zubereitung"/>
				<xs:element ref="Kommentare" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute ref="id"/>
		</xs:complexType>
	</xs:element>

	<xs:attribute type="xs:positiveInteger" name="id"/>

	<xs:element name="Kategorie">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="Name"/>
			</xs:sequence>
			<xs:attribute ref="id"/>
			<xs:attribute ref="ParentId" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:attribute type="xs:positiveInteger" name="ParentId"/>

	<xs:element name="Bilder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Bild" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Bild">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="Autor" minOccurs="0"/>
				<xs:element type="xs:anyURI" name="Quelle"/>
			</xs:sequence>
			<xs:attribute ref="width" use="required"/>
			<xs:attribute ref="height" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:attribute type="xs:integer" name="width"/>
	<xs:attribute type="xs:integer" name="height"/>

	<xs:element name="Zutaten">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Zutat" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="Portionen"/>
		</xs:complexType>
	</xs:element>

	<xs:attribute name="Portionen">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minExclusive value="0"/>
				<xs:maxInclusive value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:element name="Zutat">
		<xs:complexType>
			<xs:attribute type="xs:string" name="Name" use="required"/>
			<xs:attribute ref="Anzahl" use="optional"/>
			<xs:attribute ref="Einheit" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:attribute name="Anzahl">
		<xs:simpleType>
			<xs:union>
				<xs:simpleType>
					<xs:restriction base="xs:float"/>
				</xs:simpleType>
				<xs:simpleType>
					<xs:restriction base="xs:integer"/>
				</xs:simpleType>
			</xs:union>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="Einheit" default="">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=""/>
				<xs:enumeration value="g"/>
	                            <xs:enumeration value="Pck."/>
	                                <xs:enumeration value="EL"/>
	                                <xs:enumeration value="ml"/>
	                                <xs:enumeration value="Prise"/>
	                                <xs:enumeration value="Dose"/>
	                                <xs:enumeration value="TL"/>
	                                <xs:enumeration value="Pkt."/>
	                                <xs:enumeration value="Stk." />
	                                <xs:enumeration value="Flasche"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:element name="Zubereitung">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Zeit" minOccurs="0"/>
				<xs:element ref="Schwierigkeitsgrad" minOccurs="0"/>
				<xs:element ref="Kalorien" minOccurs="0" />
				<xs:element ref="Schritte"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Kalorien" default="keine Angabe">
		<xs:simpleType>
			<xs:union>
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger"/>
				</xs:simpleType>
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:union>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Zeit">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Vorheizen" minOccurs="0"/>
				<xs:element ref="Backen" minOccurs="0"/>
				<xs:element ref="Gehzeit" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Vorheizen">
		<xs:complexType>
			<xs:attribute ref="Minuten"/>
			<xs:attribute ref="Stunden" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Backen">
		<xs:complexType>
			<xs:attribute ref="Minuten"/>
			<xs:attribute ref="Stunden" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Gehzeit">
		<xs:complexType>
			<xs:attribute ref="Minuten"/>
			<xs:attribute ref="Stunden" use="optional"/>
			<xs:attribute ref="Tage" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:attribute name="Minuten">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minExclusive value="0"/>
				<xs:maxInclusive value="60"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="Stunden">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minExclusive value="0"/>
				<xs:maxInclusive value="24"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:attribute name="Tage">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minExclusive value="0"/>
				<xs:maxInclusive value="356"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:element name="Schwierigkeitsgrad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="simple"/>
				<xs:enumeration value="normal"/>
				<xs:enumeration value="pfiffig"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Schritte">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="step" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Kommentare">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Kommentar" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Kommentar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="KommentarAutor"/>
				<xs:element type="xs:dateTime" name="date"/>
				<xs:element type="xs:boolean" name="isHelpful" default="false"/>
				<xs:element type="xs:string" name="content"/>
				<xs:element ref="Antworten" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="KommentarAutor">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name"/>
				<xs:element ref="Avatar" minOccurs="0"/>
				<xs:element type="xs:integer" name="userLevel"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Avatar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Bild"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Antworten">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Kommentar" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== jthy/Projekt/WBA_OrderHero/src/NewXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NewXMLSchema.xsd">
  <Rezept>
    <Titel>Schokokuchen</Titel>
    <Kategorie id="11" ParentId="33">
      <Name>Backen</Name>
    </Kategorie>
    <Bilder>
    <Bild height="345" width="324">
    <Autor>Peterli</Autor>
    <Quelle>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/42942-420x280-fix-lenchen-s-schokoladenkuchen.jpg</Quelle>
    </Bild>
    </Bilder>
    <Zutaten Portionen="10">
      <Zutat Name="Butter" Anzahl="200" Einheit="g"/>
      <Zutat Name="Mehl" Anzahl="555" Einheit="g"/>
      <Zutat Name="Backpulver" Anzahl="1" Einheit="Pkt."/>
    </Zutaten>
    <Zubereitung>
    <Zeit>
    <Vorheizen Minuten="20"/>
    <Backen Minuten="60"/>
    </Zeit>
    <Schwierigkeitsgrad>normal</Schwierigkeitsgrad>
    <Kalorien>295</Kalorien>
      <Schritte>
        <step>Butter und Schokolade im Wasserbad schmelzen.</step>
        <step>Eier trennen.</step>
      </Schritte>
    </Zubereitung>
    <Kommentare>
    <Kommentar>
    <KommentarAutor>
    <Avatar>
    <Bild height="44" width="323">
    <Quelle>http://static.chefkoch-cdn.de/ck.de/avatar/</Quelle>
    </Bild>
    </Avatar>
    <userLevel>1</userLevel>
    <name>Petra</name>
    </KommentarAutor>
    <date>2012-04-17T09:20:47</date>
    <isHelpful>true</isHelpful>
    <content>Hilfeee</content>
    <Antworten>
    	<Kommentar>
     <KommentarAutor>
    <Avatar>
    <Bild height="44" width="323">
    <Quelle>http://static.chefkoch-cdn.de/ck.de/avatar/1</Quelle>
    </Bild>
    </Avatar>
    <userLevel>3</userLevel>
    <name>Lisa</name>
    </KommentarAutor>
    <date>2012-04-17T09:20:47</date>
    <isHelpful>true</isHelpful>
    <content>Hilfeee</content>
    </Kommentar>
    </Antworten>
    
    </Kommentar>
    </Kommentare>
  </Rezept>
</Rezepte>
