=== jthy/Projekt/WBA_OrderHero/src/XSD/Personenliste.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Personenliste">
<xs:complexType>
<xs:sequence>

<xs:element name="Person" maxOccurs="unbounded" minOccurs="1">
		<xs:complexType>
		<xs:sequence>
		<xs:element name="Person_ID" type="xs:int"/>
			<xs:element name="Typ">
	 			<xs:simpleType>
			    	<xs:restriction base="xs:string">
			      		<xs:enumeration value="Gastronom" />
			      		<xs:enumeration value="Lieferant" />
			   		</xs:restriction>
	  			</xs:simpleType>
	  		</xs:element>
			<xs:element name="Vorname" type="xs:string"/>
			<xs:element name="Nachname" type="xs:string"/>
			<!-- Gastronom muss über 18 sein um Käufe abzuwickeln -->
			<xs:element name="Alter">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="18" />
						<xs:maxInclusive value="100" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element ref="Betrieb"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<!-- Definitionen -->			
<xs:element name="Betrieb">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Betriebs_ID" type="xs:int" minOccurs="1" maxOccurs="1"/>
						<xs:element name="Betriebname" minOccurs="1" maxOccurs="1" type="xs:string"/>
						<xs:element name="Adresse">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="strasse" type="xs:string"/>
									<xs:element name="Hausnummer" type="xs:int"/>
									<xs:element name="PLZ">
										<xs:simpleType>
											<xs:restriction base="xs:int">
											<xs:pattern value="(D )?[0-9]{5}" />
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
</xs:element>
</xs:schema>

=== jthy/Projekt/WBA_OrderHero/src/Personenliste.xml
<?xml version="1.0" encoding="UTF-8"?>
<Personenliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Personenliste.xsd">
  <Person>
    <Person_ID>1</Person_ID>
    <Typ>Gastronom</Typ>
    <Vorname>Peter</Vorname>
    <Nachname>Lustig</Nachname>
    <Alter>33</Alter>
    <Betrieb>
      <Betriebs_ID>0</Betriebs_ID>
      <Betriebname>Betriebname</Betriebname>
      <Adresse>
        <strasse>strasse</strasse>
        <Hausnummer>0</Hausnummer>
        <PLZ>0</PLZ>
      </Adresse>
    </Betrieb>
  </Person>
   <Person>
    <Person_ID>2</Person_ID>
    <Typ>Gastronom</Typ>
    <Vorname>Lisa</Vorname>
    <Nachname>Lolli</Nachname>
    <Alter>22</Alter>
    <Betrieb>
      <Betriebs_ID>0</Betriebs_ID>
      <Betriebname>Betriebname</Betriebname>
      <Adresse>
        <strasse>strasse</strasse>
        <Hausnummer>0</Hausnummer>
        <PLZ>0</PLZ>
      </Adresse>
    </Betrieb>
  </Person>
</Personenliste>

=== jthy/Projekt/WBA_OrderHero/src/XML/Personenliste.xml
<?xml version="1.0" encoding="UTF-8"?>
<Personenliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/Personenliste.xsd">
  <Person>
    <Person_ID>0</Person_ID>
    <Typ>Gastronom</Typ>
    <Vorname>Vorname</Vorname>
    <Nachname>Nachname</Nachname>
    <Alter>0</Alter>
    <Betrieb>
      <Betriebs_ID>0</Betriebs_ID>
      <Betriebname>Betriebname</Betriebname>
      <Adresse>
        <strasse>strasse</strasse>
        <Hausnummer>0</Hausnummer>
        <PLZ>0</PLZ>
      </Adresse>
      <Art_des_Betriebes>Art_des_Betriebes</Art_des_Betriebes>
    </Betrieb>
  </Person>
</Personenliste>

=== jthy/Projekt/WBA_OrderHero/bin/Personenliste.xml
<?xml version="1.0" encoding="UTF-8"?>
<Personenliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Personenliste.xsd">
  <Person>
    <Typ>Gastronom</Typ>
    <Vorname>Peter</Vorname>
    <Nachname>Pan</Nachname>
    <Alter>100</Alter>
    <Betrieb>
      <Betriebname>Champs</Betriebname>
      <Adresse>
        <Straße>Adenaueralle</Straße>
        <PLZ>12345</PLZ>
      </Adresse>
     </Betrieb>
     </Person>
</Personenliste>
